init:
  - git config --global core.autocrlf true

environment:
  matrix:
    - nodejs_version: "4"
    - nodejs_version: "5"
    - nodejs_version: "6"
    - nodejs_version: "7"
      configuration: "publish"

matrix:
  fast_finish: true

platform:
  - x86
  - x64

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm i --ignore-scripts

before_build:
  - node --version
  - npm --version

build_script:
  - npm test

cache:
  - node_modules -> package.json
  - '%APPDATA%\npm-cache'

test: off

deploy_script:
  - ps: |
      if ($ENV:APPVEYOR_REPO_TAG_NAME -and $ENV:CONFIGURATION -eq "publish" -and $ENV:PLATFORM -eq "x64")
      {
        "//registry.npmjs.org/:_authToken=`$`{NPM_TOKEN`}" | Out-File (Join-Path $ENV:APPVEYOR_BUILD_FOLDER ".npmrc") -Encoding UTF8
        iex "npm publish --access public"
      }
  - if defined appveyor_repo_tag_name npm run release

version: "{build}"
